### ISSUE TITLE
Reversed Green and Blue variables in some of the server code

### ISSUE THREAD

**Issue by Adzam1** [ronbuist/ws2801scratch#1]
Hi, 
Thanks for putting this project together.   I am teaching some 5th grade students how to interact with a strand of WS2801 lights for a LED sign project at our school.  I found this project, and it's perfect to get them up and running using scratch. 

One issue I found is that normally we reference RGB as "red, green, blue" when making pixel change within the adafruit libraries.   In some of the lines of server code, the green and blue variables are transposed, which makes the scratch interface set the wrong colors. 

Line 72             pixels.set_pixel_rgb(pix, red, blue, green)
Line 75             pixels.set_pixel_rgb(pix, red, blue, green)
Line 85             color=Adafruit_WS2801.RGB_to_color(red,blue,green)

All these need to read (red, green, blue) for correct color selection.

**Comment by ronbuist** [comment]
Hi! You are right, of course. Except... for the specific WS2801 strand I have, I could only get it working correctly by using the order red, blue, green and hence the server code is written the way it is now. If I used the order red, green, blue, setting 0,255,0 would set the pixel to blue and 0,0,255 would set it to green. I thought it was an error in the adafruit library but apparently not all WS2801 strands are behaving identical. Let me think of an elegant way to make this configurable somehow...

Thanks for letting me know you’re using my project and thank you for reaching out regarding the colors issue.
